// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package company

import (
	"gf_demo/api/company"
)

type ControllerV1 struct{}

func NewV1() company.ICompanyV1 {
	return &ControllerV1{}
}
