// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package application

import (
	"gf_demo/api/application"
)

type ControllerV1 struct{}

func NewV1() application.IApplicationV1 {
	return &ControllerV1{}
}
