// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package feature

import (
	"gf_demo/api/feature"
)

type ControllerV1 struct{}

func NewV1() feature.IFeatureV1 {
	return &ControllerV1{}
}
