// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package suggest_skill

import (
	"gf_demo/api/suggest_skill"
)

type ControllerV1 struct{}

func NewV1() suggest_skill.ISuggestSkillV1 {
	return &ControllerV1{}
}
