// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalActivityDao is internal type for wrapping internal DAO implements.
type internalActivityDao = *internal.ActivityDao

// activityDao is the data access object for table activity.
// You can define custom methods on it to extend its functionality as you wish.
type activityDao struct {
	internalActivityDao
}

var (
	// Activity is globally public accessible object for table activity operations.
	Activity = activityDao{
		internal.NewActivityDao(),
	}
)

// Fill with you ideas below.
