// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalApplicationchatmessageDao is internal type for wrapping internal DAO implements.
type internalApplicationchatmessageDao = *internal.ApplicationChatMessageDao

// applicationchatmessageDao is the data access object for table ApplicationChatMessage.
// You can define custom methods on it to extend its functionality as you wish.
type applicationchatmessageDao struct {
	internalApplicationchatmessageDao
}

var (
	// Applicationchatmessage is globally public accessible object for table ApplicationChatMessage operations.
	Applicationchatmessage = applicationchatmessageDao{
		internal.NewApplicationChatMessageDao(),
	}
)

// Fill with you ideas below.
