// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalApplicationFileDao is internal type for wrapping internal DAO implements.
type internalApplicationFileDao = *internal.ApplicationFileDao

// applicationFileDao is the data access object for table application_file.
// You can define custom methods on it to extend its functionality as you wish.
type applicationFileDao struct {
	internalApplicationFileDao
}

var (
	// ApplicationFile is globally public accessible object for table application_file operations.
	ApplicationFile = applicationFileDao{
		internal.NewApplicationFileDao(),
	}
)

// Fill with you ideas below.
