// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalCertificateDao is internal type for wrapping internal DAO implements.
type internalCertificateDao = *internal.CertificateDao

// certificateDao is the data access object for table certificate.
// You can define custom methods on it to extend its functionality as you wish.
type certificateDao struct {
	internalCertificateDao
}

var (
	// Certificate is globally public accessible object for table certificate operations.
	Certificate = certificateDao{
		internal.NewCertificateDao(),
	}
)

// Fill with you ideas below.
