// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalCompanyDao is internal type for wrapping internal DAO implements.
type internalCompanyDao = *internal.CompanyDao

// companyDao is the data access object for table company.
// You can define custom methods on it to extend its functionality as you wish.
type companyDao struct {
	internalCompanyDao
}

var (
	// Company is globally public accessible object for table company operations.
	Company = companyDao{
		internal.NewCompanyDao(),
	}
)

// Fill with you ideas below.
