// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalCompanyplanDao is internal type for wrapping internal DAO implements.
type internalCompanyplanDao = *internal.CompanyPlanDao

// companyplanDao is the data access object for table CompanyPlan.
// You can define custom methods on it to extend its functionality as you wish.
type companyplanDao struct {
	internalCompanyplanDao
}

var (
	// Companyplan is globally public accessible object for table CompanyPlan operations.
	Companyplan = companyplanDao{
		internal.NewCompanyPlanDao(),
	}
)

// Fill with you ideas below.
