// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalCompanyaccountsDao is internal type for wrapping internal DAO implements.
type internalCompanyaccountsDao = *internal.CompanyAccountsDao

// companyaccountsDao is the data access object for table CompanyAccounts.
// You can define custom methods on it to extend its functionality as you wish.
type companyaccountsDao struct {
	internalCompanyaccountsDao
}

var (
	// Companyaccounts is globally public accessible object for table CompanyAccounts operations.
	Companyaccounts = companyaccountsDao{
		internal.NewCompanyAccountsDao(),
	}
)

// Fill with you ideas below.
