// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalCompanysubscriptionDao is internal type for wrapping internal DAO implements.
type internalCompanysubscriptionDao = *internal.CompanySubscriptionDao

// companysubscriptionDao is the data access object for table CompanySubscription.
// You can define custom methods on it to extend its functionality as you wish.
type companysubscriptionDao struct {
	internalCompanysubscriptionDao
}

var (
	// Companysubscription is globally public accessible object for table CompanySubscription operations.
	Companysubscription = companysubscriptionDao{
		internal.NewCompanySubscriptionDao(),
	}
)

// Fill with you ideas below.
