// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalEducationDao is internal type for wrapping internal DAO implements.
type internalEducationDao = *internal.EducationDao

// educationDao is the data access object for table education.
// You can define custom methods on it to extend its functionality as you wish.
type educationDao struct {
	internalEducationDao
}

var (
	// Education is globally public accessible object for table education operations.
	Education = educationDao{
		internal.NewEducationDao(),
	}
)

// Fill with you ideas below.
