// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalExperienceDao is internal type for wrapping internal DAO implements.
type internalExperienceDao = *internal.ExperienceDao

// experienceDao is the data access object for table experience.
// You can define custom methods on it to extend its functionality as you wish.
type experienceDao struct {
	internalExperienceDao
}

var (
	// Experience is globally public accessible object for table experience operations.
	Experience = experienceDao{
		internal.NewExperienceDao(),
	}
)

// Fill with you ideas below.
