// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalFeatureDao is internal type for wrapping internal DAO implements.
type internalFeatureDao = *internal.FeatureDao

// featureDao is the data access object for table feature.
// You can define custom methods on it to extend its functionality as you wish.
type featureDao struct {
	internalFeatureDao
}

var (
	// Feature is globally public accessible object for table feature operations.
	Feature = featureDao{
		internal.NewFeatureDao(),
	}
)

// Fill with you ideas below.
