// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalJobquestionDao is internal type for wrapping internal DAO implements.
type internalJobquestionDao = *internal.JobQuestionDao

// jobquestionDao is the data access object for table JobQuestion.
// You can define custom methods on it to extend its functionality as you wish.
type jobquestionDao struct {
	internalJobquestionDao
}

var (
	// Jobquestion is globally public accessible object for table JobQuestion operations.
	Jobquestion = jobquestionDao{
		internal.NewJobQuestionDao(),
	}
)

// Fill with you ideas below.
