// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalMediaDao is internal type for wrapping internal DAO implements.
type internalMediaDao = *internal.MediaDao

// mediaDao is the data access object for table media.
// You can define custom methods on it to extend its functionality as you wish.
type mediaDao struct {
	internalMediaDao
}

var (
	// Media is globally public accessible object for table media operations.
	Media = mediaDao{
		internal.NewMediaDao(),
	}
)

// Fill with you ideas below.
