// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalNotificationDao is internal type for wrapping internal DAO implements.
type internalNotificationDao = *internal.NotificationDao

// notificationDao is the data access object for table notification.
// You can define custom methods on it to extend its functionality as you wish.
type notificationDao struct {
	internalNotificationDao
}

var (
	// Notification is globally public accessible object for table notification operations.
	Notification = notificationDao{
		internal.NewNotificationDao(),
	}
)

// Fill with you ideas below.
