// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalResumeDao is internal type for wrapping internal DAO implements.
type internalResumeDao = *internal.ResumeDao

// resumeDao is the data access object for table resume.
// You can define custom methods on it to extend its functionality as you wish.
type resumeDao struct {
	internalResumeDao
}

var (
	// Resume is globally public accessible object for table resume operations.
	Resume = resumeDao{
		internal.NewResumeDao(),
	}
)

// Fill with you ideas below.
