// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalScheduleDao is internal type for wrapping internal DAO implements.
type internalScheduleDao = *internal.ScheduleDao

// scheduleDao is the data access object for table schedule.
// You can define custom methods on it to extend its functionality as you wish.
type scheduleDao struct {
	internalScheduleDao
}

var (
	// Schedule is globally public accessible object for table schedule operations.
	Schedule = scheduleDao{
		internal.NewScheduleDao(),
	}
)

// Fill with you ideas below.
