// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalSkillDao is internal type for wrapping internal DAO implements.
type internalSkillDao = *internal.SkillDao

// skillDao is the data access object for table skill.
// You can define custom methods on it to extend its functionality as you wish.
type skillDao struct {
	internalSkillDao
}

var (
	// Skill is globally public accessible object for table skill operations.
	Skill = skillDao{
		internal.NewSkillDao(),
	}
)

// Fill with you ideas below.
