// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalSuggestskillDao is internal type for wrapping internal DAO implements.
type internalSuggestskillDao = *internal.SuggestSkillDao

// suggestskillDao is the data access object for table SuggestSkill.
// You can define custom methods on it to extend its functionality as you wish.
type suggestskillDao struct {
	internalSuggestskillDao
}

var (
	// Suggestskill is globally public accessible object for table SuggestSkill operations.
	Suggestskill = suggestskillDao{
		internal.NewSuggestSkillDao(),
	}
)

// Fill with you ideas below.
