// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalUsersubscriptionDao is internal type for wrapping internal DAO implements.
type internalUsersubscriptionDao = *internal.UserSubscriptionDao

// usersubscriptionDao is the data access object for table UserSubscription.
// You can define custom methods on it to extend its functionality as you wish.
type usersubscriptionDao struct {
	internalUsersubscriptionDao
}

var (
	// Usersubscription is globally public accessible object for table UserSubscription operations.
	Usersubscription = usersubscriptionDao{
		internal.NewUserSubscriptionDao(),
	}
)

// Fill with you ideas below.
