// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// internalUserplanDao is internal type for wrapping internal DAO implements.
type internalUserplanDao = *internal.UserPlanDao

// userplanDao is the data access object for table UserPlan.
// You can define custom methods on it to extend its functionality as you wish.
type userplanDao struct {
	internalUserplanDao
}

var (
	// Userplan is globally public accessible object for table UserPlan operations.
	Userplan = userplanDao{
		internal.NewUserPlanDao(),
	}
)

// Fill with you ideas below.
